version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopeed
    environment:
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: Sabya@#429
      POSTGRES_DB: placement

    volumes:
      - pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portal -d placement"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

    
  redis:
    image: redis:7-alpine
    
    